// 1. local channel will be created by server A bes it is the initiator for the connection

const lc = new RTCPeerConnection();

//  2. creation of data channel for talking
const datachannel = lc.createDataChannel("channel");

// 3. listen to the messages on this data channel and listen to if the cannnel is open or not

datachannel.onmessage = (e) => console.log("just got a message " + e.data);
datachannel.onopen = (e) => console.log("connection opeaned !!! ");

// 4. Try to fine ICE cancidates (basically these are suport for video format, STUN & TURN server etc)

lc.onicecandidate = (e) =>
  console.log(
    "New Ice candidate! reprinting SDP" + JSON.stringify(lc.localDescription)
  );

// 5 Creation of offer, this offer will be given to server B

lc.createOffer()
  .then((o) => lc.setLocalDescription(o))
  .then((a) => console.log("set successfully"));

// ------- after this youll get a Ice candidate and your SDP will be reprinted or regenerated
// now this SDP you have to give to Server B (via whatsapp, twitter, httpcall, fetch, axios anyting )
// but we will basically copy and paste
/*
It looks like this 

New Ice candidate! reprinting SDP{"type":"offer","sdp":"v=0\r\no=- 8081324153459025915 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=candidate:2141701514 1 udp 2113937151 05ad2c18-aae4-4bbe-a6ca-c3cf02a20a67.local 52669 typ host generation 0 network-cost 999\r\na=candidate:3369707031 1 udp 2113939711 cc923a94-0aba-4b8c-8488-45bd1b85a252.local 63839 typ host generation 0 network-cost 999\r\na=ice-ufrag:t/E6\r\na=ice-pwd:qP8wabf3eM65WNMEctN7a7Fb\r\na=ice-options:trickle\r\na=fingerprint:sha-256 50:A5:61:91:1D:42:41:A6:91:2E:5E:50:7F:1F:45:5B:73:0F:9F:B0:04:E0:6D:C0:B6:F6:DC:19:EA:CC:30:15\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}

*/

// After this the work for server A is done we just have to communicate ANSWER from server B and paste it here

// This is the answer generated by server B after the steps we did on server B (REPLACE THIS ANSWER this is just example)
const answer = {
  type: "answer",
  sdp: "v=0\r\no=- 460172335637836873 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=candidate:769222893 1 udp 2113937151 8d71564a-35ae-457d-9be0-dde718606a05.local 50713 typ host generation 0 network-cost 999\r\na=candidate:4008103571 1 udp 2113939711 07275feb-2144-425b-84dc-e8ded77e4554.local 59702 typ host generation 0 network-cost 999\r\na=ice-ufrag:nHqJ\r\na=ice-pwd:8bQnGTOu++3DefyVOx8hM92P\r\na=ice-options:trickle\r\na=fingerprint:sha-256 63:2E:B5:5B:4E:A3:43:2D:8A:AB:A4:88:67:FE:9A:27:3E:48:94:D5:DB:CA:ED:24:26:6F:BF:9A:CB:F6:ED:E2\r\na=setup:active\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n",
};

lc.setRemoteDescription(answer);

datachannel.send("hello kaise ho bhai ");
